-- MySQL Script generated by MySQL Workbench
-- Thu Jun 22 19:37:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trammpo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trammpo
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema trammpo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trammpo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trammpo` DEFAULT CHARACTER SET utf8mb4 ;
USE `trammpo` ;

-- -----------------------------------------------------
-- Table `trammpo`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trammpo`.`cidade` (
  `idCidade` INT NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trammpo`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trammpo`.`estado` (
  `idEstado` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trammpo`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trammpo`.`tipo_usuario` (
  `idTipo` INT NOT NULL,
  `tipo_usuario` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trammpo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trammpo`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo_usuario_idTipo` INT NOT NULL,
  `perfil` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_tipo_usuario1_idx` (`tipo_usuario_idTipo` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_idTipo`)
    REFERENCES `trammpo`.`tipo_usuario` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `trammpo`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trammpo`.`cliente` (
  `idCliente` INT NOT NULL,
  `usuario_idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_usuario_idx` (`usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `trammpo`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trammpo`.`modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trammpo`.`modalidade` (
  `idModalidade` INT(11) NOT NULL,
  `servico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModalidade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `trammpo`.`prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trammpo`.`prestador` (
  `idPrestador` INT(11) NOT NULL AUTO_INCREMENT,
  `cnpj` INT(14) NULL DEFAULT NULL,
  `nomeFantasia` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(10000) NULL,
  `usuario_idUsuario` INT(11) NOT NULL,
  `modalidade_idModalidade` INT(11) NOT NULL,
  PRIMARY KEY (`idPrestador`),
  INDEX `usuario_idUsuario` (`usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_prestador_modalidade1_idx` (`modalidade_idModalidade` ASC) VISIBLE,
  CONSTRAINT `prestador_ibfk_1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `trammpo`.`usuario` (`idUsuario`),
  CONSTRAINT `fk_prestador_modalidade1`
    FOREIGN KEY (`modalidade_idModalidade`)
    REFERENCES `trammpo`.`modalidade` (`idModalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `trammpo`.`imagem_prestador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trammpo`.`imagem_prestador` (
  `idImagem` INT NOT NULL,
  `imagem` VARCHAR(45) NULL,
  `prestador_idPrestador` INT(11) NOT NULL,
  PRIMARY KEY (`idImagem`),
  INDEX `fk_imagem_prestador_prestador1_idx` (`prestador_idPrestador` ASC) VISIBLE,
  CONSTRAINT `fk_imagem_prestador_prestador1`
    FOREIGN KEY (`prestador_idPrestador`)
    REFERENCES `trammpo`.`prestador` (`idPrestador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `trammpo` ;

-- -----------------------------------------------------
-- Table `trammpo`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trammpo`.`email` (
  `idEmail` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuario_idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idEmail`),
  INDEX `fk_email_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_email_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `trammpo`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `trammpo`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trammpo`.`endereco` (
  `idEndereco` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_idUsuario` INT(11) NOT NULL,
  `cidade_idCidade` INT NOT NULL,
  `estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `usuario_idUsuario` (`usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_endereco_cidade1_idx` (`cidade_idCidade` ASC) VISIBLE,
  INDEX `fk_endereco_estado1_idx` (`estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `endereco_ibfk_1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `trammpo`.`usuario` (`idUsuario`),
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`cidade_idCidade`)
    REFERENCES `trammpo`.`cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_estado1`
    FOREIGN KEY (`estado_idEstado`)
    REFERENCES `trammpo`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `trammpo`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trammpo`.`telefone` (
  `idTelefone` INT(11) NOT NULL,
  `telefone` INT(11) NOT NULL,
  `usuario_idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_telefone_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `trammpo`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
